application: xiafaneventdemo
version: 1
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /gchart
  static_dir: eventdemo/gchart
- url: /.*
  script: main.application

libraries:
- name: pycrypto
  version: 2.6